services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: UlAntonCourses
      POSTGRES_USER: antonuzegov
      POSTGRES_PASSWORD: "0387"
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/UlAntonCourses
      SPRING_DATASOURCE_USERNAME: antonuzegov
      SPRING_DATASOURCE_PASSWORD: "0387"
    ports:
      - "8083:8083"

volumes:
  db_data: