spring:
  # Настройки базы данных
  datasource:
    url: jdbc:postgresql://localhost:5433/UlAntonCourses
    username: antonuzhegov
    password: 0387
    driver-class-name: org.postgresql.Driver

  # Настройки JPA (Data JPA)
  jpa:
    hibernate:
      ddl-auto: update  # АВТОМАТИЧЕСКИ создаёт таблицы!
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true  # красивый SQL в логах
    show-sql: true  # показывать SQL в консоли

# Порт нашего приложения
server:
  port: 8083

# Включаем красивый интерфейс для тестирования БД
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html